import argparse
import json
import sys
import time
from pathlib import Path
from pipeline import config, fetcher, decoder

def run_pipeline(category_slug: str = None, limit_per_sub: int = 10, dry_run: bool = False):
    try:
        categories = config.get_categories()
    except Exception as e:
        print(f"Failed to load categories config: {e}")
        sys.exit(1)

    # Filter categories to run
    to_run = categories
    if category_slug:
        to_run = [cat for cat in categories if cat["slug"] == category_slug]
        if not to_run:
            print(f"Error: Category slug '{category_slug}' not found in configuration.")
            sys.exit(1)

    output_dir = config.get_output_dir()
    print(f"Pipeline started. Output directory: {output_dir}")
    print(f"Running for {len(to_run)} categories (Dry Run = {dry_run})")

    for idx, cat in enumerate(to_run):
        slug = cat["slug"]
        subreddits = cat["subreddits"]
        
        # Introduce a sleep delay to prevent 503 spikes on the Gemini API
        if idx > 0:
            print("  Sleeping for 3 seconds to avoid API demand limits...")
            time.sleep(3)

        if dry_run:
            print(f"\n[Dry-Run] Initializing simulated data generation for {cat['name']}...")
            simulated_ideas = []
            
            try:
                simulated_ideas = decoder.generate_simulated_ideas(slug, cat["name"], subreddits)
            except Exception as e:
                print(f"  [Info] Gemini simulation failed or key not set: {e}")
                
            if not simulated_ideas:
                print("  [Info] Falling back to static mock card template...")
                simulated_ideas = [
                    {
                        "id": f"{slug}-simulated-idea",
                        "category": slug,
                        "title": f"Simulated {cat['name']} Idea",
                        "tagline": "A simulated product concept built during a dry run.",
                        "whatItIs": "This is a placeholder card generated by running the pipeline with the dry-run flag. It verifies that the crawler-LLM pipeline outputs valid JSON.",
                        "momentum": "Heating Up",
                        "momentumScore": 75,
                        "momentumWhy": "Mock data generated successfully.",
                        "difficulty": "Beginner",
                        "whyNow": "This represents a mock opportunity.",
                        "theTea": "Some developers think simulated ideas are useful for UI layout checks, while others prefer live data.",
                        "whoIsDoingIt": "Local developers testing pipelines.",
                        "gettingStarted": [
                            "Configure real Reddit credentials.",
                            "Provide a valid Gemini API Key.",
                            "Re-run the pipeline without the --dry-run flag."
                        ],
                        "tags": ["Scraper", "Mock", "Automation"],
                        "sources": [
                            {
                                "title": "How to dry run python scripts",
                                "url": "https://www.reddit.com/r/programming",
                                "subreddit": "programming",
                                "upvotes": 12,
                                "numComments": 3
                            }
                        ],
                        "lastUpdated": "2026-06-15T08:00:00Z"
                    }
                ]
            
            save_ideas(slug, simulated_ideas, output_dir)
            continue

        # Real Execution
        raw_threads = fetcher.fetch_category_data(slug, subreddits, limit_per_sub=limit_per_sub)
        
        if not raw_threads:
            print(f"No threads found or failed to fetch for {slug}. Skipping decode step.")
            continue

        decoded_ideas = decoder.decode_threads_to_ideas(slug, raw_threads)
        
        if decoded_ideas:
            save_ideas(slug, decoded_ideas, output_dir)
        else:
            print(f"Failed to generate ideas for {slug}.")

    print("\nPipeline execution complete!")

def save_ideas(category_slug: str, ideas: list, output_dir: Path):
    filepath = output_dir / f"{category_slug}.json"
    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(ideas, f, indent=2, ensure_ascii=False)
    print(f"Saved {len(ideas)} cards to {filepath}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Brew Scraper & Gemini Decoder Pipeline")
    parser.add_argument(
        "--category",
        type=str,
        default=None,
        help="Specific category slug to crawl/decode (default: runs all 14 categories)"
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=10,
        help="Number of threads to crawl per subreddit (default: 10)"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Simulate the pipeline execution and write mock JSON files without calling Reddit/Gemini APIs"
    )

    args = parser.parse_args()
    
    run_pipeline(
        category_slug=args.category,
        limit_per_sub=args.limit,
        dry_run=args.dry_run
    )
